### ISSUE TITLE
Regular Expression Denial of Service - npm audit moderate warning

### ISSUE THREAD

**Issue by kakodali** [armsteadj1/react-plastic#5]
@armsteadj1  We need to upgrade the packages as required. Please let me know if you want me to create a PR with updated packages

![image](https://user-images.githubusercontent.com/34098146/41545503-52915b02-72e9-11e8-9d68-a9711d529fbc.png)

**Comment by armsteadj1** [comment]
Sure! I can get it merged in and pushed out if you get a PR. Thanks!

**Comment by armsteadj1** [comment]
Fixed in PR #6

**Comment by kakodali** [comment]
Thanks for closing this, totally forgot
